### ISSUE TITLE
slowfi - `sendQuote` function may always revert

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-symmetrical-update-2-judging#21]
slowfi

Medium

# `sendQuote` function may always revert

## Summary
The new `sendQuote` function will always revert as `PartyAFacetImpl.sol` checks on [PartyAFacetImpl.sol#L72](https://github.com/SYMM-IO/protocol-core/blob/develop/contracts/facets/PartyA/PartyAFacetImpl.sol#L72) that is a valid affiliate. There is not task nor script that registers address(0) as a valid affiliate. Also creating a valid affiliate with address zero may lead to improper storage of collected fees. 

## Vulnerability Detail

The `sendQuoteWithAffiliate` function is designed to handle fee distribution by specifying an affiliate address. However, the previous function `sendQuote` forces the affiliate address to be zero. Due to the check at L72 on `PartyAFacetImpl.sol`, the function reverts if the affiliate is not valid. Since address(0) cannot be a valid affiliate, this scenario causes the function to fail. Moreover, attempting to create a valid affiliate with address zero would result in improper fee storage, leading to fees being stores on the storage of the zero address.

## Impact
Lack of intended operation functionality and/or improper fee handling.

## Code Snippet
`sendQuote` calls `` with address(0) as affiliate.
[PartyAFacet.sol#L132](https://github.com/SYMM-IO/protocol-core/blob/develop/contracts/facets/PartyA/PartyAFacet.sol#L132)
```solidity
	function sendQuote(
		address[] memory partyBsWhiteList,
		uint256 symbolId,
		PositionType positionType,
		OrderType orderType,
		uint256 price,
		uint256 quantity,
		uint256 cva,
		uint256 lf,
		uint256 partyAmm,
		uint256 partyBmm,
		uint256 maxFundingRate,
		uint256 deadline,
		SingleUpnlAndPriceSig memory upnlSig
	) external whenNotPartyAActionsPaused notLiquidatedPartyA(msg.sender) notSuspended(msg.sender) {
		uint256 quoteId = PartyAFacetImpl.sendQuote(
			partyBsWhiteList,
			symbolId,
			positionType,
			orderType,
			price,
			quantity,
			cva,
			lf,
			partyAmm,
			partyBmm,
			maxFundingRate,
			deadline,
			address(0),
			upnlSig
		);
```

`sendQuote` of implementation facet that may revert [PartyAFacetImpl.sol#L72](https://github.com/SYMM-IO/protocol-core/blob/develop/contracts/facets/PartyA/PartyAFacetImpl.sol#L72)
```solidity
        require(maLayout.affiliateStatus[affiliate], "PartyAFacet: Invalid affiliate");
```
## Tool used

Manual Review

## Recommendation
Consider removing this function. Or creating other workflow for address zero affiliates.

Duplicate of #22

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/SYMM-IO/protocol-core/pull/55

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
